@ECHO OFF & CHCP 936 & TITLE "清除系统垃圾"
CLS
:WORK1
    ECHO.
    ECHO.
　　ECHO 正在清除系统垃圾文件，请稍等......
　　DEL /F /S /Q %SYSTEMDRIVE%\*.TMP
　　DEL /F /S /Q %SYSTEMDRIVE%\*._MP
　　::DEL /F /S /Q %SYSTEMDRIVE%\*.LOG
　　DEL /F /S /Q %SYSTEMDRIVE%\*.GID
　　DEL /F /S /Q %SYSTEMDRIVE%\*.CHK
　　DEL /F /S /Q %SYSTEMDRIVE%\*.OLD
　　DEL /F /S /Q %SYSTEMDRIVE%\RECYCLED\*.*
　　DEL /F /S /Q %WINDIR%\*.BAK
　　DEL /F /S /Q %WINDIR%\PREFETCH\*.*
　　RD /S /Q %WINDIR%\TEMP & MD %WINDIR%\TEMP
　　DEL /F /Q %USERPROFILE%\COOKIES\*.*
　　DEL /F /Q %USERPROFILE%\RECENT\*.*
　　DEL /F /S /Q "%USERPROFILE%\LOCAL SETTINGS\TEMPORARY INTERNET FILES\*.*"
　　DEL /F /S /Q "%USERPROFILE%\LOCAL SETTINGS\TEMP\*.*"
　　DEL /F /S /Q "%USERPROFILE%\RECENT\*.*"

:WORK2
FOR %%I IN (C D E F G H) DO (
   IF EXIST "%%I:\PROGRAM FILES\腾讯游戏\QQGAME\GAMESHOW\ITEM" DEL /F/S/Q "C:\PROGRAM FILES\腾讯游戏\QQGAME\GAMESHOW\ITEM\*.*"
   IF EXIST "%%I:\DOCUMENTS AND SETTINGS\ADMINISTRATOR\LOCAL SETTINGS\APPLICATION DATA\GOOGLE\CHROME\USER DATA\DEFAULT\CACHE" DEL /F/S/Q "C:\DOCUMENTS AND SETTINGS\ADMINISTRATOR\LOCAL SETTINGS\APPLICATION DATA\GOOGLE\CHROME\USER DATA\DEFAULT\CACHE\*.*"
   IF EXIST "%%I:\PROGRAM FILES\腾讯游戏\QQGAME\DOWNLOAD" DEL /F/S/Q "C:\PROGRAM FILES\腾讯游戏\QQGAME\DOWNLOAD\*.*"
)

:END
EXIT