@ECHO OFF
	::REG ADD HKCR\LNKFILE /V ISSHORTCUT /F
	REG DELETE HKCR\PIFFILE /V ISSHORTCUT /F
	::REG ADD HKCR\INTERNETSHORTCUT /V ISSHORTCUT /F
	
	ECHO Restart explorer.exe...
	TASKKILL /F /IM EXPLORER.EXE
	ECHO Please wait for seconds...
	START "" "EXPLORER.EXE"

	ECHO Done!!
PAUSE>NULL
EXIT